### ISSUE TITLE
Custom Language

### ISSUE THREAD

**Issue by willsilvano** [dai-siki/vue-image-crop-upload#10]
How to add custom language?

**Comment by dai-siki** [comment]
:lang-ext="Object"

**Comment by willsilvano** [comment]
Do you have an example?

**Comment by dai-siki** [comment]
{
        hint: 'Click, or drag the file here',
        loading: 'Uploading……',
        noSupported: 'Browser does not support, please use IE10+ or other browsers',
        success: 'Upload success',
        fail: 'Upload failed',
        preview: 'Preview',
        btn: {
            off: 'Cancel',
            close: 'Close',
            back: 'Back',
            save: 'Save'
        },
        error: {
            onlyImg: 'Image only',
            outOfSize: 'Image exceeds size limit: ',
            lowestPx: 'The lowest pixel in the image: '
        }
    }

**Comment by willsilvano** [comment]
` <my-upload field="img" :lang-ext="btn: {
off: 'Cancel',
close: 'Close',
back: 'Back',
save: 'Save'
},"></my-upload>`

This way?

**Comment by dai-siki** [comment]
`<my-upload field="img" :lang-ext="{btn: { off: 'Cancel', close: 'Close', back: 'Back', save: 'Save' }}"></my-upload>`
This way! 
I don't know if this grammar is current. `:param="a:b"`

**Comment by willsilvano** [comment]
I have do this way, but still show the zh language :/

**Comment by dai-siki** [comment]
`:lang-type="en"`
The default language is chinese, so you need to declare the next language type

**Comment by dai-siki** [comment]
Sorry, this is a bug on the program that has been fixed, please update version 1.3.4
