### ISSUE TITLE
upload.css

### ISSUE THREAD

**Issue by edwinnnss** [dai-siki/vue-image-crop-upload#11]
on upload-2.vue stlye section importing `./upload.css`, but its loaded as localhost/upload.css
![image](https://cloud.githubusercontent.com/assets/13062493/23786601/8f85a228-05a0-11e7-8978-43b518243d3d.png)

can you help me ?

**Comment by dai-siki** [comment]
The reason for this problem may be 'vue-loader', Relatively simple method, you can directly copy the contents of 'upload.css'  to the 'upload-2.vue'
