### ISSUE TITLE
可以自定义文件的name么？

### ISSUE THREAD

**Issue by callmesoul** [dai-siki/vue-image-crop-upload#111]
定义了field后，`filename` 和`name` 都为field的值了，可以更改单独更改name值？

**Comment by callmesoul** [comment]
文件的name一般为`file`,怎么会跟着文件名filename走呢？

**Comment by likangda** [comment]
请问是如何解决的？

**Comment by chongyangwang** [comment]
请问是如何解决的？ @likangda  @callmesoul
