### ISSUE TITLE
能否自定义预览窗口的尺寸和大小？

### ISSUE THREAD

**Issue by huangqiang1363** [dai-siki/vue-image-crop-upload#113]

**Comment by dai-siki** [comment]
在可预见的将来，应该不能

**Comment by ggepenyan** [comment]
Please add an option for this. It is very important really. It would be nice.
I tried to do it with custom css(changed the width of the `vicp-img-container`) but the thing is that after that image doesnt' fit to container. It goes outside of preview window. Please help me, I really need it
