### ISSUE TITLE
上传成功再次打开窗口停留在上传最后一步

### ISSUE THREAD

**Issue by gee1k** [dai-siki/vue-image-crop-upload#120]
上传成功再次打开窗口停留在上传最后一步

当前版本 `2.3.1`

**Comment by gee1k** [comment]
需要手动调用`off` 方法来解决

**Comment by sdsno** [comment]
怎么手动调off方法?

**Comment by gee1k** [comment]
给组件加一个ref，然后 this.$refs[refName].off()
```
<avatar-uploader ref="uploader"></avatar-upload>

this.$refs.uploader.off()
```

**Comment by sdsno** [comment]
大神,我加完就是自动关闭了,再点还是最后一步,不知道哪弄错了

**Comment by gee1k** [comment]
这是我的做法

![image](https://user-images.githubusercontent.com/12059800/42634047-c19cf6f8-8614-11e8-9758-52052887cbaf.png)

**Comment by PauloChina** [comment]
this.$refs.uploader.off()   确实可以 感谢楼上
这么重要的东西竟然在文档里看不到

**Comment by Kagashino** [comment]
看了源码，当前版本可以直接调用setState方法
```
 this.$refs.uploader.setState(1)
```
