### ISSUE TITLE
Is this compatible with nuxt?

### ISSUE THREAD

**Issue by jericopulvera** [dai-siki/vue-image-crop-upload#127]

**Comment by hardjob** [comment]
create a plugin 
//avatar.js
import Vue from 'vue';
import myUpload from 'vue-image-crop-upload';

Vue.component('avatar', myUpload);
--------
then in your component

**Comment by gregbenner** [comment]
plugins: [
{ src: '~plugins/vue-avatar-cropper', mode: 'client' }
]
