### ISSUE TITLE
upload image have bug

### ISSUE THREAD

**Issue by LiDengHui** [dai-siki/vue-image-crop-upload#13]
I have find this component have bug in `upload-2.vue`

```
let client = new XMLHttpRequest();
                client.open('POST', url, true);
                client.onreadystatechange = function() {
                    if (this.readyState !== 4) {
                        return;
                    }
                    if (this.status === 200) {
                        resolve(JSON.parse(this.responseText));
                    } else {
                        reject(this.status);
                    }
                };
                client.upload.addEventListener("progress", uploadProgress, false); //监听进度
				// 设置header
	            if (typeof headers == 'object' && headers) {
	                Object.keys(headers).forEach((k) => {
	                    client.setRequestHeader(k, headers[k]);
	                })
	            }
                client.send(fmData);
```
the `client.upload` is Object-` {}`  ,  find the `addEventListener` is undefined ,
but I delete upload to 'client.addEventListener("progress", uploadProgress,false)',the
progress not change.

Thank you, if you reply to me

**Comment by dai-siki** [comment]
请提供一下你的浏览器类别，IE10以上应该都是兼容的

**Comment by LiDengHui** [comment]
chrome

**Comment by dai-siki** [comment]
![image](https://cloud.githubusercontent.com/assets/18674462/24086717/c04a6c5c-0d4f-11e7-99ea-0342426ed330.png)

上面是在chromel浏览器中打印出来的结果，更多可以参考。[https://developer.mozilla.org/zh-CN/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest](url)

**Comment by LiDengHui** [comment]
![image](https://cloud.githubusercontent.com/assets/8112598/24087135/1d9c061c-0d56-11e7-969f-33cb259008a1.png)

**Comment by dai-siki** [comment]
可能和打包工具有关系，最好能查下打包后的文件，单纯这个语法是正确的，否则测试用例应该也会报错才对。或者你可以一步步console.log来调试，先看看是不是client这个变量有问题

**Comment by LiDengHui** [comment]
有没有可能是浏览器环境不支持addEventListener方法，能改成和onprecsss兼容模式吗

**Comment by dai-siki** [comment]
请在你的浏览器控制台输入 console.log(new XMLHttpRequest().upload.addEventListener)

**Comment by LiDengHui** [comment]
不好意思，知道不是组件的原因，很奇怪，在我的页面里是undefined，但是在另外一个里面有值

**Comment by dai-siki** [comment]
也许是你引用了其他的插件，导致更改了XMLHttpRequest().upload对象

**Comment by LiDengHui** [comment]
![image](https://cloud.githubusercontent.com/assets/8112598/24087709/7097145e-0d5d-11e7-94af-2d5e8cfb13e2.png)


谢谢。找到问题了

**Comment by Geek-Jokey** [comment]
> ![image](https://cloud.githubusercontent.com/assets/8112598/24087709/7097145e-0d5d-11e7-94af-2d5e8cfb13e2.png)
> 
> 谢谢。找到问题了

我也遇到了同样的问题，可以透露一下是怎么解决的吗？

**Comment by LiDengHui** [comment]
找到在哪引入的MockXMLHttpRequest
删掉他
