### ISSUE TITLE
how to clear preview

### ISSUE THREAD

**Issue by chamra** [dai-siki/vue-image-crop-upload#133]
Is there a way to clear the preview and go back to upload view ?

**Comment by chamra** [comment]
after a click save is there a way to go to step 1?

**Comment by Tyler-RCSD** [comment]
I also have this problem.  After a successful upload the window hides but if someone wants to upload again the window opens back up on the last step.  How can we send it back to step 1?

**Comment by Korris** [comment]
add ref to your component

avatar-uploader ref="uploader"></avatar-upload

then add this to Uploadsuccess methods
this.$refs.uploader.setStep(1)
