### ISSUE TITLE
请问 如何实现动态改变语言类型呢？

### ISSUE THREAD

**Issue by Taosome** [dai-siki/vue-image-crop-upload#142]
不能动态改变组件的语言类型，请问有什么好的方法吗？

**Comment by jttjt** [comment]
父组件中已经watch到langType的值改变了，但是这个组件还是初始化状态时的语言类型

**Comment by dai-siki** [comment]
一个好的办法是 改变langType的时候，用v-if重新初始化组件

**Comment by dai-siki** [comment]
一个好的办法是 改变langType的时候，用v-if重新初始化组件
