### ISSUE TITLE
如何将URL指向后端服务器的URL？

### ISSUE THREAD

**Issue by CanonInDW** [dai-siki/vue-image-crop-upload#155]
您好！非常荣幸能够使用您的上传图片组件，在调试的过程中遇到了一个问题，希望您能解答。
我的项目目前是用vue+element做前端，用django做后端，当我在设置my-upload的url时，传到的真实地址是前端的BASE_URL+my-upload中的url，请问，如何才能自己自定义URL？由其是将BASE_URL修改到后端地址？
非常感谢！

**Comment by dai-siki** [comment]
组件url参数可以直接传进去
