### ISSUE TITLE
支持移动端

### ISSUE THREAD

**Issue by guntertien** [dai-siki/vue-image-crop-upload#16]
您好，这个组件很炫酷，想问一下楼大大，什么时候支持移动端适配，基于vue的移动webApp现在比较流行。谢谢

**Comment by dai-siki** [comment]
这个问题已经提出过多次，但还是抱歉，最近不太有时间和精力去做，请等待一段时间吧，大概不会太久，希望5月来临前可以完成

**Comment by dai-siki** [comment]
今天尝试去兼容移动端，发现不如重写一个，所以暂时搁置……
