### ISSUE TITLE
可以去掉弹框么？

### ISSUE THREAD

**Issue by hooray** [dai-siki/vue-image-crop-upload#180]
就是默认不是弹框的形式，而是可以直接在页面上使用。

如果需要弹框可以让用户自行实现，尤其是在中后台里使用时，搭配 UI 框架，可以轻松做到风格统一，不然就会比较难受了。

比如搭配 element-ui 使用，就会发现遮罩层的颜色深浅不统一，element点击遮罩层是可以关闭弹框的，但该组件就不行。

**Comment by dai-siki** [comment]
这个确实不太好弄
