### ISSUE TITLE
国家化语言文件传入不生效

### ISSUE THREAD

**Issue by ccj-mlp** [dai-siki/vue-image-crop-upload#182]
### 根据源文件添加了一个国际化文件，然后把改国际化对象文件通过参数langExtc传入，没有显示覆盖，还是显示的是默认值，打印组件内部的langExt属性已经有传入的值了，但是界面没有生效

**Comment by dai-siki** [comment]
langExt只能传入当前语言的值，比如
```
:lang-ext="{hint: '点击，或拖动图片至此处(*^_^*)'}"
```
