### ISSUE TITLE
Need to clear the error message

### ISSUE THREAD

**Issue by RoamIn** [dai-siki/vue-image-crop-upload#19]
- Choose one image，then turn off the network. It will show uploading error message
- Turn on network, it will upload success, and show success message
- Now, there are two message

Follows the screenshots:

- ![error](https://cloud.githubusercontent.com/assets/11537595/24835836/4630e7ca-1d3f-11e7-9f68-8e0f86ab98ad.png)
- ![continueupload](https://cloud.githubusercontent.com/assets/11537595/24835866/0769be80-1d40-11e7-81e6-bf166bfed109.png)
- ![finally](https://cloud.githubusercontent.com/assets/11537595/24835868/0da78a16-1d40-11e7-8248-9f0c8ae0d2dd.png)

**Comment by dai-siki** [comment]
Bug has been fixed, thank you advice
