### ISSUE TITLE
找不到 upload.css 文件

### ISSUE THREAD

**Issue by corwien** [dai-siki/vue-image-crop-upload#22]
你好，直接安装该组件后，找不到upload.css 文件：
`Failed to load resource: the server responded with a status of 404  upload.css (Not Found)`

什么原因呢？

**Comment by corwien** [comment]
![2017-04-15 17 19 57](https://cloud.githubusercontent.com/assets/16316462/25062517/122ce2c4-2200-11e7-87e3-56742880a066.png)

这个是具体的截图

**Comment by dai-siki** [comment]
已经就这个问题进行了优化，请更新@1.3.8
