### ISSUE TITLE
upload-3.vue 中 ki prop 默认值应该是 字符串“0”，实际上是 数字0，版本3.0.1

### ISSUE THREAD

**Issue by iFTY-R** [dai-siki/vue-image-crop-upload#235]
![图片](https://user-images.githubusercontent.com/40951966/113841588-6f341300-97c4-11eb-9ff4-b4630d0a0657.png)

 "vue-image-crop-upload": "^3.0.1",    这个地方有问题，引用之后就会报错

**Comment by dai-siki** [comment]
好的 我看下

**Comment by dai-siki** [comment]
已发版 3.02
