### ISSUE TITLE
初始化时报错 [Vue warn]: Failed to resolve directive: el

### ISSUE THREAD

**Issue by kolf** [dai-siki/vue-image-crop-upload#25]
从上面复制的代码，运行时报 [Vue warn]: Failed to resolve directive: el，弹框能正常弹出来。但是点上传的时候报Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "value" 错误。vue 版本是2.2.2 ,  vue-image-crop-upload版本是1.3.8

**Comment by dai-siki** [comment]
import myUpload from 'vue-image-crop-upload/upload-2.vue';
vue2 要引入这个组件，文档里有写。
