### ISSUE TITLE
如果不是通过本地上传，而是从另外一个地方选择一张图片来裁剪，上传，请问有办法吗？

### ISSUE THREAD

**Issue by jkchao** [dai-siki/vue-image-crop-upload#27]
你好，现在一个需求是要求不仅仅是通过本地选择图片文件，还可以从其他地方选择一张图片裁剪上传，类似于微博那种从相册选择一张图片，然后裁剪，请问如果用这个插件，有什么办法实现吗？

**Comment by dai-siki** [comment]
你是说复制图片链接地址？我试试吧

**Comment by jkchao** [comment]
en

**Comment by dai-siki** [comment]
canvas使用图片有同源限制，网络图片基本上都无法使用，要实现这个功能需要后台来紧密配合，用户输入图片url，后台取得该图片保存到本站，再把链接返回给前端，这样就太繁琐和具体了，不是这个组件的本意。所以抱歉，你可以fork一份，自己尝试去实现一下。

**Comment by jkchao** [comment]
ok，谢了。
