### ISSUE TITLE
请教下报错的问题

### ISSUE THREAD

**Issue by sexyios** [dai-siki/vue-image-crop-upload#3]
你好，我用的是cli的模板工具，引用你的插件
![oi6hz u 9qulb 7h u 3](https://cloud.githubusercontent.com/assets/8684040/21969960/5cd32694-dbdd-11e6-9969-2ff30e703be5.png)
![isz0vr5 yiqm 2rug4d47](https://cloud.githubusercontent.com/assets/8684040/21969986/7e118a1c-dbdd-11e6-9741-ac495e93168b.png)
跟你推荐的写法一样的啊  但是引用报错，能劳烦帮忙看一下吗  谢谢啊

**Comment by dai-siki** [comment]
首先确保你使用的是vue@1+
其次，我在文档里推荐的写法是直接在根实例中引用该组件的写法，如果像你现在这样要再次封装的话，在组件中data应该是个function（参考[vue1文档组件选项问题](http://v1-cn.vuejs.org/guide/components.html#组件选项问题)），其他的错误像参数未定义，可以自行修改下
