### ISSUE TITLE
测试时没有点击按钮，页面直接弹出框，并且没有文字

### ISSUE THREAD

**Issue by alan-zhang-** [dai-siki/vue-image-crop-upload#32]
![3333](https://cloud.githubusercontent.com/assets/5202716/26762894/992ce636-497c-11e7-895e-d1b316470f6d.png)

**Comment by dai-siki** [comment]
没有文字，可能是语言配置写错了。
直接弹出，是因为控件的展示是value值来控制的，需要你传一个参数进去。

**Comment by alan-zhang-** [comment]
直接弹出解决了。弹窗是没有文字的，但是上传图片后的文字都可见。

**Comment by dai-siki** [comment]
请把你相关的代码贴出来，要不无法定位问题

**Comment by alan-zhang-** [comment]
你好，解决了，原来高度不够，我把height去掉后就好了：
![110](https://cloud.githubusercontent.com/assets/5202716/26814448/3a9f243e-4ab8-11e7-8a66-0ca8907a3794.png)
