### ISSUE TITLE
能不能添加设置默认图片的功能

### ISSUE THREAD

**Issue by lzming1989** [dai-siki/vue-image-crop-upload#35]

**Comment by dai-siki** [comment]
不是太明白，能详细解释下吗

**Comment by lzming1989** [comment]
我修改了您的插件，三个步奏的页面同时显示在页面上，有没有什么方法，能让第二步页面在加载时默认读取一个路径的图片，就是跳过第一步打开本地图片，我现在有设置默认图片的需求

**Comment by dai-siki** [comment]
可以添加一个默认图片url的prop属性，来作为没有图源时的默认图片
