### ISSUE TITLE
可否支持 IE9

### ISSUE THREAD

**Issue by WildDylan** [dai-siki/vue-image-crop-upload#36]

**Comment by dai-siki** [comment]
用到的关键API不支持，所以不考虑支持IE9，会很麻烦

**Comment by WildDylan** [comment]
项目需要，那可以大致跟我们讲下，如果在您的基础之上修改的话，如何替换掉FileReader么？
如果替换成功，我们也会将代码贡献进来。

**Comment by dai-siki** [comment]
和后端合作，先上传，再返回图片地址，然后继续，我只能想到这个办法。还有ajax上传文件，ie9也不支持，需要用iframe方案替代
