### ISSUE TITLE
使用vue单文件组件时，组件无法显示

### ISSUE THREAD

**Issue by aaron0713** [dai-siki/vue-image-crop-upload#37]
使用vue单文件组件时upload组件窗体无法弹出，需要吧这个组件嵌套在model-dialog组件中，跟随dialog同时弹出才能显示。

**Comment by dai-siki** [comment]
正常import是可以的呀，不知道你是怎么使用的，能给出更具体的描述或代码吗

**Comment by aaron0713** [comment]
Set_UserHomePage.vue 文件：
`<template>
    <div id='Set_UserHomePage'>
        <a class="btn" @click="toggleShow">set avatar</a>
        <mu-dialog :open="show">
            <my-upload field="img"
                v-model="show"
                :width="300"
                :height="300"
                url="/upload"
                :params="params"
                :headers="headers"
                img-format="png"></my-upload>
        </mu-dialog>
        <img :src="imgDataUrl">
    </div>
</template>

<script>
import myUpload from 'vue-image-crop-upload/upload-2.vue';
export default {
    name: 'Set_UserHomePage',
    data () {
        return {
            show:false,
            params:{},
            headers:{},
            imgDataUrl:""
        }
    },
    components: {
			'my-upload': myUpload
		},
    methods: {
			toggleShow(){
                this.show=!this.show
            }
		}

}
</script>

<style>

</style>`

如去去掉外层的mu-dialog组件，上传组件就无法显示

**Comment by dai-siki** [comment]
从目前的信息，我也找不出原因所在/(ㄒoㄒ)/~~

**Comment by aaron0713** [comment]
又测试了一下，显示出来了，但是显示到屏幕之外的一个DIV（这个DIV和upload组件的父级DIV是并列关系）中了，可以不可以吧这个upload组件的dom提升到body的一级子元素。

![qq 20170714120958](https://user-images.githubusercontent.com/11188521/28198035-99f6f84c-688d-11e7-9296-e647e0f75eaf.png)

**Comment by dai-siki** [comment]
据我所知没有这样的操作，只能你把控件标签声明到不被父元素影响的位置
