### ISSUE TITLE
请问要怎么重新给上传按钮定义事件呢，我上传图片需要跨域？

### ISSUE THREAD

**Issue by Sophiajiajia** [dai-siki/vue-image-crop-upload#40]
请问要怎么重新给上传按钮定义事件呢，我上传图片需要跨域？

**Comment by dai-siki** [comment]
上传按钮的事件就是控件显示与否，控件绑定的value值（布尔类型）改变。上传图片不能跨域，跨域会失败的（canvas的toDataURL方法有限制），如果确实涉及到网络图片，就必须要先上传服务器，返回服务器保存的新地址，然后继续操作，这个你可以自己更改下这个控件

**Comment by Sophiajiajia** [comment]
在哪个文件改啊。。。xhr.js？

**Comment by dai-siki** [comment]
如果是vue1，更改upload.vue，如果vue2，更改upload-2.vue
