### ISSUE TITLE
Offset zooming and language pack

### ISSUE THREAD

**Issue by nicolasvahidzein** [dai-siki/vue-image-crop-upload#41]
Hello Dai-siki, thanks for this very nice plugin. Can i ask your help.

When i load an image it zooms unevenly from the side but in the preview the image looks fine.

Also, how and were do i load the translation files?

Finally, i am uploading all my data at the same time using a form, is there a way to handle the upload in another part of the page and not inside vue-image-crop-upload?

Thank you very much.

**Comment by dai-siki** [comment]
Hello nico!

The first question, I do not have a good understanding, do you have the relevant screenshot?

The language pack problem mentioned in the document, you can use the "langExt" attribute, need to pass in an object, the format is similar to:
![image](https://user-images.githubusercontent.com/18674462/28707872-a4ec6762-73ac-11e7-93f9-a72a8626a2f0.png)

The third question, you can write a separate interface to store the avatar, and then use the returned link to submit the form. Or I can modify this plugin, so you can cancel the last file upload, use the picture dataURL to submit, of course, you can own dataURL into binary files. How do you choose?

**Comment by nicolasvahidzein** [comment]
Thank you Dai siki, i will take a look.

Are you busy? I'm looking for someone to coach me and help from time to time. I'm curious to see if you have time and how much you would charge for lessons, can you pm me on skype? nzein19 is my handle.

**Comment by dai-siki** [comment]
My English is very poor and I'm sorry to help you. Thank you very much for believing me and having good luck

**Comment by nicolasvahidzein** [comment]
It's ok i don't mind, i have developpers from all over the world working with me. Do you have skype? Can we talk? Please add me.

**Comment by zhenizhui** [comment]
just go!

don't be shy 😆 

HA HA~
