### ISSUE TITLE
Cannot read property 'fileinput' of undefined

### ISSUE THREAD

**Issue by martijnhiemstra** [dai-siki/vue-image-crop-upload#42]
I get the following errors:

Cannot read property 'fileinput' of undefined
and 
Cannot read property 'canvas' of undefined

What is the problem?

**Comment by dai-siki** [comment]
Maybe you imported the version wrong, if you are vue2, should be imported like this
`import myUpload from 'vue-image-crop-upload/upload-2.vue';`
