### ISSUE TITLE
Give possibility to crop but not upload

### ISSUE THREAD

**Issue by valerymelou** [dai-siki/vue-image-crop-upload#46]
We should be able to crop the image and not upload it directly to the server. Maybe by performing the upload only if `url` prop is evaluated to true.
The solution to the issue #21  is not acceptable in this case because the upload will still occur.
I can make a PR for this if needed.

**Comment by dai-siki** [comment]
Thank you, your opinion is great, I will consider doing the next optimization as soon as possible

**Comment by dai-siki** [comment]
Has been optimized， @2.0.1
