### ISSUE TITLE
More useful arguments for handlers of crop-success

### ISSUE THREAD

**Issue by valerymelou** [dai-siki/vue-image-crop-upload#49]
First thank you for making this component.

Actually `crop-success` is triggered with the following arguments: `createImgUrl`, `field` and `ki`. I have a use case here where I want to display the cropped image and wait for the user to click on a button before performing the upload. The upload must be done as a normal upload so I'm gonna need to do something like what you did in `upload()`
`fmData.append(field, data2blob(createImgUrl, mime), field + '.' + imgFormat);`
Is it possible to change the arguments sent to `crop-success` handlers so that they can be used to do some like that and also display the cropped image?

**Comment by dai-siki** [comment]
You need to just transcode the picture, so you can import the transcoding function as follows.

```
import data2blob from 'vue-image-crop-upload/utils/data2blob.js'
```

**Comment by valerymelou** [comment]
Got it. Many thanks.
