### ISSUE TITLE
ERROR: [Vue warn]: "key" is a reserved attribute and cannot be used as component prop. 

### ISSUE THREAD

**Issue by bigperson** [dai-siki/vue-image-crop-upload#5]
[Vue warn]: "key" is a reserved attribute and cannot be used as component prop. 
(found in component <image-crop-upload> at  vue-image-crop-upload\upload-2.vue)

Vue version 2.0.6

**Comment by dai-siki** [comment]
This has been fixed in @ 1.3.1，Thank you!
