### ISSUE TITLE
Error while uglifying using Webpack

### ISSUE THREAD

**Issue by vividvilla** [dai-siki/vue-image-crop-upload#52]
Webpack throws this error while uglifying the code. 

```
ERROR in static/js/kite.4.76951c1af06af38f3f25.js from UglifyJs
Unexpected token: name (opts) [./~/vue-image-crop-upload/utils/effectRipple.js:9,0][static/js/kite.4.76951c1af06af38f3f25.js:3870,5]
```

In my opinion the library should not be using `effectRipple` because most of the users might not prefer it.

**Comment by blyleven** [comment]
+ 1

**Comment by dai-siki** [comment]
My guess is utify plug-in can not resolve ES6, so I am dealing with the error file, remove es6 related grammar, you can try, I do not know what the results will be

**Comment by blyleven** [comment]
For now I've forked it and removed the ripple effect. Don't need that anyway.

**Comment by valerymelou** [comment]
Just ran into this. What's the recommended solution?

**Comment by valerymelou** [comment]
I ran into the same issue a few days ago and it was fixed after I ran `npm update` in my project.
