### ISSUE TITLE
1 上传图片背景为空 ， 裁剪时背景会变成黑色， 2 希望能够支持旋转功能 

### ISSUE THREAD

**Issue by yangfan0095** [dai-siki/vue-image-crop-upload#62]
1 上传图片背景为空 ， 裁剪时背景会变成黑色， 2 希望能够支持旋转功能

**Comment by kevinlvhsl** [comment]
我遇到的问题：
设定宽高为400*300，上传png图片也是400*300，
但是图片是有进度条控制大小缩放的，默认没有拖放填满，右边就会出现透明部分。
请问怎么设定默认下就是最大，可以填满右边
![图片](http://zhongantech-dev-out.oss-cn-hzfinance.aliyuncs.com/zat:boardDisplay:bfcbf784b327578654947bb684c32a74_originalFile_file.png)
![原图大小是400*300](http://zhongantech-dev-out.oss-cn-hzfinance.aliyuncs.com/zat:boardDisplay:6b39a4b48dd625743f181afecbb0ca8d_searchPageThumbnail_file.png)

**Comment by dai-siki** [comment]
@yangfan0095 已经合并了你的分支，发布了新版，非常感谢。

@kevinlvhsl 你说的问题确实存在，当宽高比设为4:3时会出现bug，已经修复，可以更新最新版本，感谢提出问题
