### ISSUE TITLE
Show error message returned from Server.

### ISSUE THREAD

**Issue by bjoct16** [dai-siki/vue-image-crop-upload#68]
Currently , error message is returned from language file. Can you please guide me to return error message sent by server in json format.

**Comment by dai-siki** [comment]
![image](https://user-images.githubusercontent.com/18674462/32204075-33c68016-be22-11e7-9f4a-a32449d99938.png)
推荐你fork一份，然后修改upload-2.vue中js部分最下面这里的上传部分的处理，errowMsg字段就是要展示的错误
