### ISSUE TITLE
建议几个优化

### ISSUE THREAD

**Issue by shen100** [dai-siki/vue-image-crop-upload#71]
首先，非常感谢作者提供的这个上传组件，用着很舒服。

提几个建议:

1. 增加个参数，用来控制上传完成后，弹框是否自动关闭，目前还得再点一下关闭
![image](https://user-images.githubusercontent.com/2443162/32982979-2625635a-ccc8-11e7-82d1-359a2305673d.png)

2.拖动滑竿，或点击+, -号，放大，缩小的速度过慢，例如，我点一下+号，只是放大了一点点，这个是否也能提供个参数来控制?
![image](https://user-images.githubusercontent.com/2443162/32982989-83fc21da-ccc8-11e7-99cf-131cfe3b3402.png)

**Comment by dai-siki** [comment]
1、上传成功后会有一个回调函数crop-upload-success，可以在回调里设置关闭
2、可能是因为你的图片像素太低，放大的上限就是图片原本的大小，因此会看上去比较慢
