### ISSUE TITLE
缓存

### ISSUE THREAD

**Issue by Alluretear** [dai-siki/vue-image-crop-upload#8]
图片比较复杂情况下，放大缩小或者拖动图片后会出现图片重叠
![qq 20170227104859](https://cloud.githubusercontent.com/assets/26051070/23347059/5e80a32c-fcda-11e6-9bd9-dbebec654395.png)

**Comment by dai-siki** [comment]
感谢你的反馈，已经修复这个问题（有透明度图片剪裁时会出现重影）。请更新@1.3.2版本。
