### ISSUE TITLE
dynamic url is possible ?

### ISSUE THREAD

**Issue by blubMe** [dai-siki/vue-image-crop-upload#82]
i want to ask , how to make url dynamic following the Id user 
example : 

the localstorage : 
`window.localStorage.getItem('key');` and the value of key is 4 

then this is the example url   :

`<avatar-upload field="avatar" v-model="show" :width="300" langType="en" :height="300" url="http://localhost:8000/api/v1/user/"`

My question is how to make url dynamic followed our register id like this :

`<avatar-upload field="avatar" v-model="show" :width="300" langType="en" :height="300" url="http://localhost:8000/api/v1/user/4"`

**Comment by dai-siki** [comment]
``` html
<avatar-upload :url="url">
```

``` js
var id = window.localStorage.getItem('key');
var baseUrl = "http://localhost:8000/api/v1/user/";
data:{
  url:  baseUrl + id,
}
```

**Comment by blubMe** [comment]
ahhh thx u very much :100: worked well
